### ISSUE TITLE
Ikke mulig å avslå invite 😬

### ISSUE THREAD

**Issue by Emilima** [blankoslo/Pizza.v2#46]
Det ser ut som det av og til ikke er mulig å avslå invite. Pizzabot-admin må inn i grensesnittet og avslå manuelt.

<img width="723" alt="Screenshot 2023-01-31 at 09 25 53" src="https://user-images.githubusercontent.com/21928971/215718316-1d899b43-61d1-429f-a861-a783d98a45da.png">

**Comment by AndreasJJ** [comment]
Tror problemet ligger i at det noen ganger tar flere sekunder for svaret å bli registrert. Litt usikker på hvorfor, men her ser vi det tok nesten 8 sekunder, mens slack vil ha svar innen 3 sekunder. Mulig handleren må skrives om til å svare med en "vennligst vent" melding før den prosesserer, for deretter å oppdatere invitasjonen når den er ferdig.

![Screen Shot 2023-03-13 at 18 22 47](https://user-images.githubusercontent.com/15128509/224779141-81468b31-1166-47ee-bfc9-0e95c2027b5c.png)

**Comment by AndreasJJ** [comment]
Gjorde noen endringer for å prøve å få ned responstiden. Denne gangen kom den ned i 3.8 sekunder. Nå som boten er en multi-workspace app så må den hente ut data fra databasen om den workspacen og lagre det i `installationStore` første gang en bruker fra den workspacen sender et event (Deretter blir den lagret fram til heroku rebooter dynoen eller man redeployer). Har gjort enda en endring jeg håper skal senke responstiden. Hvis dette ikke funker så blir et alternativ å hente data for alle workspace og cache det lokalt ved startup av boten slik at man slipper den initielle lastingen på første event.
![Screen Shot 2023-03-13 at 21 04 42](https://user-images.githubusercontent.com/15128509/224819959-09caa255-1e22-4ef8-a05e-171d30ab1d42.png)
